[window]
padding = { x = 5, y =10 }
dynamic_padding = true
# decorations = "none" # Без рамки
opacity = 0.8
decorations_theme_variant = "None"
# level = "AlwaysOnTop" # Если охота видеть поверх остальных окон
dimensions = { columns = 75, lines = 15 }

[font]
size = 15

[font.normal]
family = "JetBrainsMonoNL Nerd Font"
style = "Regular"

[cursor.style]
shape = "Beam"
blinking = "On"

[cursor]
blink_interval = 1000
thickness = 0.17

[mouse]
hide_when_typing = true
